apiVersion: v1
kind: Secret
metadata:
  name: edusence-backend-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vZWR1c2VuY2UtZGI6NTQzMi9lZHVzZW5jZQ==
  SPRING_DATASOURCE_USERNAME: ZWR1c2VuY2U=
  SPRING_DATASOURCE_PASSWORD: ZWR1c2VuY2U=
  AWS_S3_ACCESS_KEY: Y2hhbmdlLW1l
  AWS_S3_SECRET_KEY: Y2hhbmdlLW1l
  GEMINI_API_KEY: Y2hhbmdlLW1l
